### ISSUE TITLE
Chrome Store 30 days till punt

### ISSUE THREAD

**Issue by joeytroy** [team-inbox/inbox-reborn#54]
Once again Google Chrome Store is ready to break us off again.

Hi there,

We wanted to let you know that your item is at risk of being removed from the Chrome Web Store. Please find the details below.

Item name: Inbox Reborn theme for Gmail™

Item ID: bkphmihkdbdgedlaflnkhnmnmibffomf

Violation(s):

Impersonation:

Violation reference ID: Red Nickel
Violation: Impersonating or mimicking the following entity through item’s metadata/UI:
"Inbox Reborn theme for Gmail"
"Title,description,code "
How to rectify: Remove the violating content.
Relevant section of the program policy:
Don't pretend to be someone else, and don't represent that your product is authorized by, endorsed by, or produced by another company or organization. [(learn more)](https://developer.chrome.com/webstore/program_policies#content_policies)

Use of Permissions:

Violation reference ID: Purple Potassium
Violation: Requesting but not using the following permission(s):
storage
How to rectify: Remove the above permission(s)
Relevant section of the program policy:
Request access to the narrowest permissions necessary to implement your Product's features or services. Don't attempt to "future proof" your Product by requesting a permission that might benefit services or features that have not yet been implemented. [(learn more)](https://developer.chrome.com/webstore/program_policies#permissions)

Important information about resubmission:

Please make the necessary changes within 30 days in order to avoid removal.

**Comment by jonrandy** [comment]
I guess second one is simple. I actually don't think we need it. The first one is trickier as it is likely subjective... what do they want us to change? The name? The wording of the extension description? The icon? The colours?

This is some gatekeeping bullshit

**Comment by g60madman** [comment]
@jonrandy I have no clue what to do at this point for the name, we dealt with this before and Google keeps kicking us in the pants.  What kicks my ass is you have this crap in the Google Store that doesn't work at all but it's not being banned by Google?!?!

https://chrome.google.com/webstore/detail/google-inbox-theme/iopddlldblihladdmldkpejpkcliajbe?hl=en

Ok so back on point, here is an extension made by a former Google employee
https://chrome.google.com/webstore/detail/simplify-gmail/pbmlfaiicoikhdbjagjbglnbfcbcojpj

Maybe we come up with a name like the following?

Team Inbox Presents: Inbox Reborn
Team Inbox Presents: Inbox Reborn Theme

And then I can update the overview a little more with more content maybe? Just some thoughts.

**Comment by g60madman** [comment]
@jonrandy Ok I resubmitted but was rejected due to the storage permission. They took the updated information I added into the description so the name is OK now thank goodness 👍

Hi there,

We regret to inform you that the most recent submission of your item was rejected. Please find the details below.


Item name: Inbox Reborn theme for Gmail™

Item ID: bkphmihkdbdgedlaflnkhnmnmibffomf

Violation(s):

Use of Permissions:

Violation reference ID: Purple Potassium

Violation: Requesting but not using the following permission(s):

storage

How to rectify: Remove the above permission(s)

Relevant section of the program policy:

Request access to the narrowest permissions necessary to implement your Product's features or services. Don't attempt to "future proof" your Product by requesting a permission that might benefit services or features that have not yet been implemented. (learn more)

**Comment by jonrandy** [comment]
I haven't had a chance to test it, but I don't think we need this permission. I have a feeling that the extension will work without it, from what I've read

**Comment by jonrandy** [comment]
Just did a really quick test (remove the permission, load unpacked in Chrome) - everything still works fine. Options are saved and loaded as normal. I don't think we need the 'storage' permission - pretty sure it is safe to delete

**Comment by g60madman** [comment]
@jonrandy can you push that those changes? I'll test and verify and resubmit to Google.

**Comment by g60madman** [comment]
Thanks brother. I'll test and repost to Google tonight.

**Comment by joeytroy** [comment]
@jonrandy issue is closed and updated in Chrome Store!!

**Comment by jonrandy** [comment]
Good stuff! 👍
