### ISSUE TITLE
Extension is being applied to chat/ url endpoint and removing the New Chat button.

### ISSUE THREAD

**Issue by djjorjinho** [team-inbox/inbox-reborn#85]
This Extension is being applied to chat/ url endpoint and removing the New Chat button from the Google Chat UI.
Can you fix this please?

**Comment by joeytroy** [comment]
@djjorjinho I loaded your version of the extension but I don't see a difference with the Google Chat window. I wonder if Google is releasing this slow to the masses. Can you send me a screen shot of what it looks like?

**Comment by deepfriedfilth** [comment]
@joeytroy I just tested this PR and it will fix the issues related to Google Chat, at least when accessed via chat.google.com (which forwards to https://mail.google.com/chat/u/0/#chat/home) since his tweak will contain the extension to Gmail.

@djjorjinho I did notice that our injected Reminder button functions for a temporary work around until Joey can merge your PR and push out a new version.

Although, the problem of a hidden New Chat button does persist, since it uses the same CSS selector as the original Compose button that's hidden and replaced with our own. I noticed this independently about a month ago and started playing around with some CSS to address this issue that I'll try and wrap up this week.

**Comment by djjorjinho** [comment]
Thanks for checking @deepfriedfilth ! I didn't realize the Reminder Button was doing that good catch :)

**Comment by joeytroy** [comment]
@deepfriedfilth should I merge in @djjorjinho commit or just wait for yours to complete?

**Comment by deepfriedfilth** [comment]
@joeytroy you're fine to merge #86 immediately but maybe leave this issue open in the meantime?
